name: Build and Publish

on: push

jobs:
  tag-release:
    if: ${{ github.ref == 'refs/heads/DART-1411-versioning-diab' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Version compose file
        run: make version-pipeline-config
      - name: Tag a release
        uses: twosixlabs-dart/dart-tag-release@v3.0.38
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          release_version: ${{ format('1.0.{0}', github.run_number) }}